services:
  - type: web
    name: LoveRjXMusic
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    envVars:
      - key: API_ID
        value: your_api_id
      - key: API_HASH
        value: your_api_hash
      - key: BOT_TOKEN
        value: your_bot_token
      - key: OWNER_ID
        value: your_owner_id
      - key: SESSION_NAME
        value: your_session_string
